
version: '2.1'
services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}
    hostname: ${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}
    image: cirepo/gitlab:10.8.1-ce.0
    networks:
      local-network:
        ipv4_address: 172.16.238.21
        ipv6_address: 2001:3984:3989::21
    ports:
    - "${GITLAB_SHELL_SSH_PORT:-20022}:${GITLAB_SHELL_SSH_PORT:-20022}"
    - "${GIT_HTTP_PORT:-10080}:${GIT_HTTP_PORT:-10080}"
    restart: always
    volumes:
    # for auto repo init
    - data:${GIT_VOLUME:-/app/gitlab/data}
    - ${WORKSPACE_ON_HOST:-../../}:${GIT_VOLUME:-/app/gitlab/data}/workspace
    # keep gitlab's data
    - etc:/etc/gitlab
    - log:/var/log/gitlab
    - opt:/var/opt/gitlab
    #- ${HOME}/.ci-and-cd/${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}/etc/gitlab:/etc/gitlab
    #- ${HOME}/.ci-and-cd/${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}/var/log/gitlab:/var/log/gitlab
    #- ${HOME}/.ci-and-cd/${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}/var/opt/gitlab:/var/opt/gitlab
    environment:
    - CONFIGSERVER_WEBHOOK_ENDPOINT=${CONFIGSERVER_WEBHOOK_ENDPOINT:-http://oss-configserver.local:8888/monitor}
    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-root_pass}
    - GITLAB_SHELL_SSH_PORT=${GITLAB_SHELL_SSH_PORT:-20022}
    - GIT_ADMIN_PASSWORD=${GIT_ADMIN_PASSWORD:-user_pass}
    # 'admin' is preserved by gitlab
    - GIT_ADMIN_USERNAME=${GIT_ADMIN_USERNAME:-user}
    - GIT_DEPLOY_KEY=${GIT_DEPLOY_KEY:-/app/gitlab/data/default_deploy_key.pub}
    - GIT_HOSTNAME=${GIT_DOMAIN:-gitlab}.${INFRASTRUCTURE:-local}
    - GIT_HTTP_PORT=${GIT_HTTP_PORT:-10080}
    - GIT_VOLUME=${GIT_VOLUME:-/app/gitlab/data}
    - GIT_WORKSPACE=${GIT_VOLUME:-/app/gitlab/data}/workspace
    - SKIP_AUTO_REPO_INIT=${SKIP_AUTO_REPO_INIT:-true}

# test:
#export GITLAB_ROOT_PASSWORD=root_pass
#export GITLAB_SHELL_SSH_PORT=20022
#export GIT_ADMIN_PASSWORD=user_pass
#export GIT_ADMIN_USERNAME=user
#export GIT_HTTP_PORT=10080
#export GIT_VOLUME=/tmp
#docker-compose up gitlab-test
#source ./docker/gitlab_utils.sh
#echo $(git_service_login root root_pass)
#curl --header "Authorization: Bearer $(git_service_login root root_pass)" http://gitlab.local:10080/api/v4/projects
#docker-compose down -v
#
#  gitlab-test:
#    image: gitlab/gitlab:10.7.3-ce.0
#    container_name: ${GIT_DOMAIN:-gitlab-test}.${INFRASTRUCTURE:-local}
#    hostname: ${GIT_DOMAIN:-gitlab-test}.${INFRASTRUCTURE:-local}
#    ports:
#    - "${GITLAB_SHELL_SSH_PORT:-20022}:22"
#    - "${GIT_HTTP_PORT:-10080}:80"
#    environment:
#    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-root_pass}
#    #volumes:
#    # for script develop & debug
#    #- ./docker/git_init.sh:/app/gitlab/git_init.sh
#    #- ./docker/entrypoint.sh:/app/gitlab/entrypoint.sh
#    #- ./docker/gitlab_utils.sh:/app/gitlab/gitlab_utils.sh


networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      - subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  etc:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/etc
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
  opt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/opt
      o: bind
