
version: '2.1'
services:
  gitlab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_APT_MIRROR=${IMAGE_ARG_APT_MIRROR:-mirrors.163.com}
    container_name: ${CONTAINER_HOST_NAME:-gitlab}
    environment:
    - CONFIGSERVER_WEBHOOK_ENDPOINT=${CONFIGSERVER_WEBHOOK_ENDPOINT:-http://config-server:8888/monitor}
    - CONTAINER_HOST_NAME=${CONTAINER_HOST_NAME:-gitlab}
    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-root_pass}
    - GITLAB_SHELL_SSH_PORT=${GITLAB_SHELL_SSH_PORT:-20022}
    - GIT_ADMIN_PASSWORD=${GIT_ADMIN_PASSWORD:-user_pass}
    # 'admin' is preserved by gitlab
    - GIT_ADMIN_USERNAME=${GIT_ADMIN_USERNAME:-user}
    - GIT_DEPLOY_KEY=${GIT_DEPLOY_KEY:-/app/gitlab/data/default_deploy_key.pub}
    - GIT_HTTP_PORT=${GIT_HTTP_PORT:-10080}
    - GIT_VOLUME=${GIT_VOLUME:-/app/gitlab/data}
    - GIT_WORKSPACE=${GIT_VOLUME:-/app/gitlab/data}/workspace
    - SKIP_AUTO_REPO_INIT=${SKIP_AUTO_REPO_INIT:-true}
    hostname: ${CONTAINER_HOST_NAME:-gitlab}
    image: cirepo/gitlab:10.8.1-ce.0
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.gitlab}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/gitlab/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.21}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::21}
    ports:
    - "${GITLAB_SHELL_SSH_PORT:-20022}:${GITLAB_SHELL_SSH_PORT:-20022}"
    - "${GIT_HTTP_PORT:-10080}:${GIT_HTTP_PORT:-10080}"
    restart: always
    volumes:
    # for auto repo init
    - data:${GIT_VOLUME:-/app/gitlab/data}
    - ${WORKSPACE_ON_HOST:-../../}:${GIT_VOLUME:-/app/gitlab/data}/workspace
    # keep gitlab's data
    - etc:/etc/gitlab
    - log:/var/log/gitlab
    - opt:/var/opt/gitlab
    #- ${HOME}/.ci-and-cd/${CONTAINER_HOST_NAME:-gitlab}/etc/gitlab:/etc/gitlab
    #- ${HOME}/.ci-and-cd/${CONTAINER_HOST_NAME:-gitlab}/var/log/gitlab:/var/log/gitlab
    #- ${HOME}/.ci-and-cd/${CONTAINER_HOST_NAME:-gitlab}/var/opt/gitlab:/var/opt/gitlab

# test:
#export GITLAB_ROOT_PASSWORD=root_pass
#export GITLAB_SHELL_SSH_PORT=20022
#export GIT_ADMIN_PASSWORD=user_pass
#export GIT_ADMIN_USERNAME=user
#export GIT_HTTP_PORT=10080
#export GIT_VOLUME=/tmp
#docker-compose up gitlab-test
#source ./docker/gitlab_utils.sh
#echo $(git_service_login root root_pass)
#curl --header "Authorization: Bearer $(git_service_login root root_pass)" http://gitlab:10080/api/v4/projects
#docker-compose down -v
#
#  gitlab-test:
#    image: gitlab/gitlab:10.7.3-ce.0
#    container_name: ${CONTAINER_HOST_NAME:-gitlab-test}
#    hostname: ${CONTAINER_HOST_NAME:-gitlab-test}
#    ports:
#    - "${GITLAB_SHELL_SSH_PORT:-20022}:22"
#    - "${GIT_HTTP_PORT:-10080}:80"
#    environment:
#    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD:-root_pass}
#    #volumes:
#    # for script develop & debug
#    #- ./docker/git_init.sh:/app/gitlab/git_init.sh
#    #- ./docker/entrypoint.sh:/app/gitlab/entrypoint.sh
#    #- ./docker/gitlab_utils.sh:/app/gitlab/gitlab_utils.sh


networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  etc:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/etc
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/log
      o: bind
  opt:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/opt
      o: bind
